apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: kube-apiserver-check
  namespace: canary-checker
spec:
  schedule: "@every 2m"
  http:
    - name: apiserver-alive
      url: https://kubernetes.default.svc/healthz
      tlsConfig:
        insecureSkipVerify: true
      responseCodes: [401, 200]
