apiVersion: v1
kind: ConfigMap
metadata:
  name: pv-storage-below-5
  namespace: monitoring
  labels:
    grafana_alert: "1"
data:
  pv-storage-below-5.yaml: |
    apiVersion: 1
    groups:
        - orgId: 1
          name: infrastructure
          folder: Longhorn
          interval: 5m
          rules:
            - uid: aftnip1g5z01sf
              title: Running out of storage
              condition: C
              data:
                - refId: A
                  relativeTimeRange:
                    from: 600
                    to: 0
                  datasourceUid: prometheus
                  model:
                    editorMode: code
                    expr: |-
                        (kubelet_volume_stats_available_bytes{persistentvolumeclaim=~".*"}
                          / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~".*"}) * 100
                    instant: false
                    interval: ""
                    intervalMs: 1000
                    legendFormat: __auto
                    maxDataPoints: 43200
                    range: true
                    refId: A
                - refId: reducer
                  queryType: expression
                  datasourceUid: __expr__
                  model:
                    conditions:
                        - evaluator:
                            params:
                                - 0
                                - 0
                            type: gt
                          operator:
                            type: and
                          query:
                            params: []
                          reducer:
                            params: []
                            type: min
                          type: query
                    datasource:
                        name: Expression
                        type: __expr__
                        uid: __expr__
                    expression: A
                    intervalMs: 1000
                    maxDataPoints: 43200
                    reducer: min
                    refId: reducer
                    type: reduce
                - refId: C
                  queryType: expression
                  datasourceUid: __expr__
                  model:
                    conditions:
                        - evaluator:
                            params:
                                - 5
                            type: lt
                          operator:
                            type: and
                          query:
                            params:
                                - C
                          reducer:
                            params: []
                            type: last
                          type: query
                    datasource:
                        type: __expr__
                        uid: __expr__
                    expression: reducer
                    intervalMs: 1000
                    maxDataPoints: 43200
                    refId: C
                    type: threshold
              noDataState: NoData
              execErrState: Error
              for: 5m
              annotations:
                description: Running out of storage please expand the PV
                summary: Storage in a PV is below 5 procent
              labels: {}
              isPaused: false
              notification_settings:
                receiver: Pontus Jirbratt
