apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iss-tracker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/98pontan/rke2-gitops.git
    path: apps/iss-tracker
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: iss-tracker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true