apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
spec:
  project: infra
  sources:
    - repoURL: https://github.com/rancher/local-path-provisioner.git
      targetRevision: v0.0.37   # pin to a specific release tag
      path: deploy/chart/local-path-provisioner
      helm:
        valueFiles:
          - $values/values/local-path-provisioner/values.yaml
    - repoURL: https://github.com/98pontan/rke2-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
