apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-gpu-device-plugin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://nvidia.github.io/k8s-device-plugin
    chart: nvidia-device-plugin
    targetRevision: 0.14.4
    helm:
      releaseName: nvidia-device-plugin
      values: |
        image:
          repository: nvcr.io/nvidia/k8s-device-plugin
          tag: v0.14.4
        nodeSelector: {}
        tolerations: []
        affinity: {}
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: gpu-resources
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
