image:
  repository: quay.io/keycloak/keycloak
  tag: "26.6.4"

replicas: 1

command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--http-enabled=true"
  - "--http-port=8080"
  - "--hostname-strict=false"
  - "--proxy-headers=xforwarded"     # trust X-Forwarded-* from nginx ingress
  - "--hostname=keycloak.local"  # this is the hostname that will be used in the ingress

database:
  vendor: postgres
  hostname: keycloak-postgres
  port: 5432
  database: keycloak
  username: keycloak
  existingSecret: keycloak-db-secret   # uses key "password" by default — matches yours

extraEnv: |
  - name: KC_BOOTSTRAP_ADMIN_USERNAME
    value: admin
  - name: KC_BOOTSTRAP_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-admin-secret
        key: admin-password

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod   # match your ClusterIssuer name
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  rules:
    -
      host: keycloak.local     # <-- replace with your actual domain
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - keycloak.local       # <-- replace with your actual domain
      secretName: keycloak-tls
