apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-runner-config-reg
  namespace: devops-ci
data:
  config.yaml: |
    log:
      level: info
    container:
      docker_host: "unix:///var/run/docker.sock"
    server:
      connections:
        devops-cluster:
          url: "https://forgejo.pontus-homelab.space"
          uuid: "b335e561-6951-4f1a-8b1f-7bbcc78cc08c"
          token: "f545e98c4186d19905e9e4d0c02ecf92133a11b2"
          labels:
            - "ubuntu-latest:docker://node:lts"
            - "self-hosted"
