
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo-runner
  namespace: devops-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forgejo-runner
  template:
    metadata:
      labels:
        app: forgejo-runner
    spec:

      # Mount the baremetal node's native Docker socket & a runtime cache folder
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: runner-data
        emptyDir: {}
      - name: runner-config-vol
        configMap:
          name: forgejo-runner-config-reg

      # Step 1: Discover and Register the runner via K8s Internal DNS
      containers:
      - name: runner
        image: data.forgejo.org/forgejo/runner:12
        command: ["forgejo-runner", "daemon", "--config", "/config/config.yaml"]
        securityContext:
          privileged: true
          runAsUser: 0
          runAsGroup: 0
        # env:
        # - name: URL
        #   # K8s Internal Service Discovery (Service Name . Namespace . svc . cluster . local)
        #   value: "http://forgejo-http:3000"
        # - name: FORGEJO_RUNNER_REGISTRATION_TOKEN
        #   value: "aa32890b1efde5e6e0127e38feba20411d7a5135"
          # valueFrom:
          #   secretKeyRef:
          #     name: forgejo-runner-token
          #     key: token

        volumeMounts:
        - name: runner-config-vol
          mountPath: /config
        - name: runner-data
          mountPath: /data
        - name: docker-socket
          mountPath: /var/run/docker.sock
